### ISSUE TITLE
Handling large Xliff files?

### ISSUE THREAD

**Issue by fvet** [rvanbekkum/vsc-xliff-sync#31] opened 2019-11-04 08:50 UTC
I have an Xliff file of approx. 30 Mb. When running 'Sync Translation Units', apparently nothing happens. How can I check the extension is actually updating / working / failing? Any experience with larg Xliff files?

![image](https://user-images.githubusercontent.com/25268332/68109873-f3a5a680-feeb-11e9-9e63-157d8895d9ce.png)

**Comment by rvanbekkum** [comment] 2019-11-09 14:17
Looked into this earlier this week. For such large XLIFF files syncing takes some time, e.g., over 5 minutes per sync.

I could add a progress notification based on [vscode.window.withProgress](https://github.com/Microsoft/vscode-extension-samples/tree/master/progress-sample) from the VS Code API to inform which target file is currently being synced, so that you at least know it is still running.

![sync-progress](https://user-images.githubusercontent.com/7383241/68529935-0103cc00-0304-11ea-8d23-c93d33203c95.gif)

I already got that working to just show that the file _is_ being synced, but I am running into a bug to also update the progress bar on top of that.
As soon as the documents are loaded (with `vscode.workspace.openTextDocument` from the VS Code API), updating the progress bar stops working.

As a sidenote: there is also a limitation imposed by VS Code to limit the max. file size to 50MB. See also [this issue](https://github.com/jjuback/gc-excelviewer/issues/49). Files of ~30 MB should still work though.

**Comment by fvet** [comment] 2019-11-12 12:42
Having the progressbar would be helpfull. This would at least give us some more info about the sync being performed.

**Comment by rvanbekkum** [comment] 2019-11-16 19:40
I have released the notification/toast that shows that a sync is in progress for a target file in version 0.3.3.

For the "Extension host terminated unexpectedly." message you get, I can't tell what the issue is yet.
What I did notice though is that the sync can into weird errors, _only if_ a large XLIFF file is opened in the editor before the command is ran.
Maybe you could check whether the same applies to you? (i.e., try to run a sync. with and without opening a large XLIFF file beforehand)

Does the sync. of your large translation files always run into this error? If so, it might indeed be helpful if you could provide this sample to me, so that I can investigate further.

**Comment by fvet** [comment] 2019-11-18 08:16
To test (and exclude any 'AL extension' impact), I've opened just the 'translations' folder in VSCode (with a modified settings.json for the xliffSync settings) and successfully started syncing the xlf files (without the source file being opened / loaded). However, somewhere in the syncing process, the target xlf file gets opened and some minutes after that, the "Extension host terminated unexpectedly." message is raised again.  I'll forward the xlf file asap.

In addition, when opening an xlf file and running "Check for Need Work Translations", the "Extension host terminated unexpectedly." message also appears.

PS: Does the progress bar also show when running the "Check for Need Work Translations" (or missing translations) command?

**Comment by rvanbekkum** [comment] 2019-11-20 10:14
Thank you for sending the file, I will look into it after the Techdays 😉.

> PS: Does the progress bar also show when running the "Check for Need Work Translations" (or missing translations) command?

It does not show when using the "Check for Missing Translations" or "Check for Need Work Translations" command.

**Comment by fvet** [comment] 2019-11-20 10:26
Thanks ;)
FYI: Seems like PoEdit got problems as well with larger files (they generated temp files of 51 GB :) ) but they got them fixed recently.

**Comment by rvanbekkum** [comment] 2019-11-30 17:35
I've looked further into the issue. I have been able to sync the base/.g file to target files, but it takes quite a while to sync.
The error "Extension host terminated unexpectedly." does not always show up but if it does it appears to be a memory issue, i.e., from the console: `FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory`.

I know it can be expected that the extension consumes quite some memory as syncing the files is quite an extensive/thorough task, but I don't think it should require that much memory even for files this big.
I'm not yet sure on how to identify it just yet, but I wanted to give you an update on the issue.

**Comment by GregoryAA** [comment] 2020-02-27 09:27
Hello Rob, 

I also run into this issue. But in my case the cause  was  in wrong settings

"xliffSync.missingTranslation": "",

When I restarted VS code  I received the same error about host extension.

Also I want to note what if I change this setting to :

"xliffSync.missingTranslation": " "  and will restart vscode , I  will see wrong decoration in all files in my workspace. 

![image](https://user-images.githubusercontent.com/45356755/75427750-1e62b180-5958-11ea-887d-716f38a94b5d.png)

These are my settings:

    "xliffSync.findBySource": true,
    "xliffSync.missingTranslation": " ",
    "xliffSync.findBySourceAndDeveloperNote": true,
    "xliffSync.copyFromSourceForSameLanguage": true,
    "xliffSync.autoCheckNeedWorkTranslations": true,
    "xliffSync.autoCheckMissingTranslations": true

I looked for  the solution to make target tag in this format <target state="needs-translation"></target> with  orange decoration. Current format <target state="needs-translation"/> doesn't suite for me, because I need to add close  target tag, although I could be only add the translation there.

There is a third point:

 I can't import translation from BC Base Application.nl-NL.xlf (64 Mb)
Nothing happening. Could you also  add the progress bar there?
I tried to copy the pare correct translation units from Base application file to new xlf file and start import. In this case all works correct. I think the cause in large file size.


PS:
I can split  issue to separate requests if needed.

**Comment by rvanbekkum** [comment] 2020-02-27 11:29
Hi @GregoryAA,
Thank you for your message.

> "xliffSync.missingTranslation": " " and will restart vscode , I will see wrong decoration in all files in my workspace.

1. Concerning this issue, this seems to be a bug. For the decoration the XLIFF Sync extension uses the same code from the Angular Localization Helper this extension is based on. It seems however that the decoration was never restricted to just XLIFF files. I think we'll need to fix that, could you file a new issue for that?

> I looked for the solution to make target tag in this format with orange decoration. Current format doesn't suite for me, because I need to add close target tag, although I could be only add the translation there.
2. I don't think I understand what you mean here just yet, could you explain? If it is that you want to change what the decoration should be, then you could use the `xliffSync.decoration` setting to customize the decoration to your needs (please see the default value in the README as an example). If it is something completely different you'd like to do, just let me know.

> I can't import translation from BC Base Application.nl-NL.xlf (64 Mb)
Nothing happening. Could you also add the progress bar there?

3. This is due to VSCode not being able to handle files larger than 50 MB. I think to get this working, one option is that I'd implement the sync. procedure in .NET/PS and have the VSCode extension integrate with that. It will take me some time to implement that though.

**Comment by GregoryAA** [comment] 2020-02-27 13:57
1. Created new one https://github.com/rvanbekkum/vsc-xliff-sync/issues/39
2. Sorry GitHub hide my format :)  

I looked for the solution to make target tag in this format `<target state="needs-translation"></target> ` with orange decoration. Current format `<target state="needs-translation"/>` doesn't suite for me, because I need to add closing target tag `</target>`, although I could be only add the translation there.
I tried to set `"xliffSync.missingTranslation": "Translate Me"`. It gave me the closing tag`</target>`, but in this case code decoration  doesn't show.

![image](https://user-images.githubusercontent.com/45356755/75450750-6dbcd800-5980-11ea-95b8-a9a6494eed5c.png)

3. Many thanks. Since most translation units are already in the Base application, we really need the feature to transfer from there them

**Comment by fvet** [comment] 2020-07-27 13:16
@GregoryAA 3. A possible workaround: What we do to re-use the Base Application translations is to import the base.xlf files via PoEdit in the Translation Memory. Then opening your custom xlf files in PoEdit and use 'Pre-Translate'. It will scan the translation memory and apply the matching translations.

@rvanbekkum 3. Any plans / timing on moving the current sync logic to .NET/Ps to speed up things? Syncing a 26 Mb xlf file to one language takes approx. 20+ minutes. Would be nice if we could speed up this part (or run a similar sync via PS / background script to automate this.) 

Ideally, if we could integrate this as part of our CI/CD process, that would be even better. Imagine a scheduled pipeline (for each of our 35 apps) that could compile the app, generate the g.xlf file and sync the changes to the target language xlf files. In case of any updates, we could create a new branch with the updated xlf file to be translated.

**Comment by rvanbekkum** [comment] 2020-07-28 10:59
@fvet I made a start a few weeks ago to create a PS version of XLIFF Sync, but did not continue it yet. I'll see if I can pick this up later this week; we're probably going to need it as well. There might be some performance improvements, but even then I think it may still take some time to sync. files this big.

![ps-xliff-sync](https://user-images.githubusercontent.com/7383241/88656618-e4493780-d0d0-11ea-9956-659f973bfbb7.png)

I've been thinking on integrating it into build pipelines as well, but I think a PS version will be more suitable for that purpose than the VSCode/TypeScript version. It might be nice to be able to add to have checks for missing translations and problems in a build pipeline that can be reported as warnings after a build has finished.

I've found other PS-solutions, although none for syncing trans-units or with the same capabilities.

**Comment by rvanbekkum** [comment] 2020-08-02 20:32
My plans are currently as follows:
1. Create and release PS-version of XLIFF Sync, probably end of August 2020. You will find the source code on GitHub (repository: [rvanbekkum/ps-xliff-sync](https://github.com/rvanbekkum/ps-xliff-sync)) as soon as I have something worth sharing.
2. Create Azure DevOps tasks that use the PS-functions. You could also invoke the functions via the PowerShell task (until Azure DevOps task have been released).
3. Maybe integrate the PS-version into vsc-xliff-sync, i.e., letting the VSCode extension invoke the PS-functions for syncing and other tasks.

**Comment by rvanbekkum** [comment] 2020-09-03 18:06
The PowerShell version is optimized for large files. It creates maps/dictionaries as a preprocessing step which significantly improves on the time complexity, i.e., I think the current vsc-xliff-sync implementation approximates O(n^2) while the optimization implemented in ps-xliff-sync brings it down to O(n) (with n being the number of translation units).
The actual time it takes to sync. files can increase quite a bit the more options (`findBy...`) you enable.
I'll probably port some of the optimizations back into the VSCode version (when I've got the time and feel like it), but for now you may want to try the PowerShell version for large files.

**Comment by fvet** [comment] 2020-09-06 09:15
Hey Rob, very big thanks for the new PS version! 

I've tested it on larger xliff files (30mb+) and the results is very fast (3-4 minutes) compared to the VSCode functions (25+ minutes). This will definitly be a time saver.

**Comment by rvanbekkum** [comment] 2021-02-06 22:29
Changes for this are now also ready for the VSCode extension and will be shipped in the next release!
This significantly speeds up syncing XLIFF files in VSCode.

**Comment by rvanbekkum** [comment] 2021-02-21 16:49
Shipped in v1.0.0.

**Closed by rvanbekkum** 2021-02-21 16:49 UTC
Labels: enhancement, ships-in-future-update

**Comment by wintak** [comment] 2022-11-07 19:20
is it possible to have multiple base files and Sync `Sync-XliffTranslations -sourcePath "C:\MyProject\My Project.g.xlf" -targetPath "C:\MyProject\My Project.nl-NL.xlf" ` in XliffSync extension in VS code?

**Comment by rvanbekkum** [comment] 2022-11-08 08:01
> is it possible to have multiple base files and Sync `Sync-XliffTranslations -sourcePath "C:\MyProject\My Project.g.xlf" -targetPath "C:\MyProject\My Project.nl-NL.xlf" ` with XliffSync extension in VS code?

Yes, that should work. If the base files have different `original` attributes, then XLIFF Sync will only sync to target files with the same value for this attribute (this is the default, but it can be disabled using the `xliffSync.matchingOriginalOnly` setting).

**Comment by wintak** [comment] 2022-11-08 20:21
Thank you!
